version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "rust-bison-skeleton/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "tests/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "scripts/"
    schedule:
      interval: "daily"
