on: [push, pull_request]

name: lint

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: install bison
        run: |
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: codegen
        run: cargo build

      - name: run rustfmt
        run: rustfmt --check **/*.rs

      - name: run clippy
        run: cargo clippy --features=examples
