name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: setup bison
        uses: bison-packages/install-bison@v1
        with:
          version: '3.8.2'

      - name: codegen
        run: cargo build

      - name: run rustfmt
        run: rustfmt --check **/*.rs

      - name: run clippy
        run: cargo clippy --features=examples
