on: [push, pull_request]

name: tests

jobs:
  tests:
    name: run tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: install bison
        run: |
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          bison --version

      - name: run tests
        run: cd tests && cargo test
